let name = "𝑅𝑎𝑚";
let school = "𝙼𝚊𝚜𝚊𝚒";
let grade = "𝟷𝟸𝘵𝘩 𝘎𝘳𝘢𝘥𝘦";
let section = '𝖢';
let rollno = 21;
let maths = 97;
let physics = 80;
let chemistry = 93;
console.log("***************************");
console.log("*        REPORT CARD      *");
console.log("****************************");
console.log("* Name      =   %s        *", name);
console.log("* School    =   %s      *", school);
console.log("* Grade     =   %s *", grade);
console.log("* Section   =   %s          *", section);
console.log("* Rollno    =   %d         *", rollno);
console.log("* Maths     =   %d         *", maths);
console.log("* Physics   =   %d         *", physics);
console.log("* Chemistry =   %d         *", chemistry);
console.log("****************************");